"use client";
import {useEffect,useState} from "react";import DashboardNav from "@/components/DashboardNav";import {useMember} from "@/hooks/useMember";import {getMyWithdrawals,requestWithdrawal,Withdrawal} from "@/lib/dashboard";
export default function Withdrawals(){const {member:m,loading}=useMember();const [rows,setRows]=useState<Withdrawal[]>([]),[msg,setMsg]=useState("");const available=m?Math.max(0,(m.totalEarning||0)-(m.withdrawnAmount||0)):0;
 async function load(){if(m)setRows(await getMyWithdrawals(m.uid))}useEffect(()=>{load()},[m]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!m)return;const f=new FormData(e.currentTarget),amount=Number(f.get("amount")),method=String(f.get("method")) as "upi"|"bank";if(!Number.isFinite(amount)||amount<500||amount>available)return setMsg("Amount must be at least ₹500 and cannot exceed available balance.");
 const pending=rows.filter(x=>x.status==="pending").reduce((a,b)=>a+b.amount,0);if(amount>available-pending)return setMsg("Your pending withdrawals already reserve part of this balance.");
 await requestWithdrawal({uid:m.uid,email:m.email,amount,method,upiId:String(f.get("upiId")||""),accountName:String(f.get("accountName")||""),accountNumber:String(f.get("accountNumber")||""),ifsc:String(f.get("ifsc")||"")});setMsg("Withdrawal request submitted for admin review.");(e.currentTarget as HTMLFormElement).reset();await load()}
 if(loading||!m)return <main className="shell"><div className="panel">Loading…</div></main>;
 return <main className="shell"><DashboardNav/><div className="dash"><div className="eyebrow">Payout center</div><h2 className="dashTitle">Withdraw earnings</h2><div className="notice">Available balance: <b>₹{available.toLocaleString("en-IN")}</b>. Minimum request: ₹500.</div><form className="panel inlinePanel" onSubmit={submit}><div className="field"><label>AMOUNT</label><input name="amount" type="number" min="500" max={available} required/></div><div className="field"><label>PAYOUT METHOD</label><select name="method"><option value="upi">UPI</option><option value="bank">Bank / IMPS</option></select></div><div className="field"><label>UPI ID (FOR UPI)</label><input name="upiId"/></div><div className="field"><label>ACCOUNT HOLDER (FOR BANK)</label><input name="accountName"/></div><div className="field"><label>ACCOUNT NUMBER</label><input name="accountNumber"/></div><div className="field"><label>IFSC</label><input name="ifsc"/></div><button className="btn">Request withdrawal →</button>{msg&&<p className="sub">{msg}</p>}</form><h3>Withdrawal history</h3><table className="table"><thead><tr><th>Amount</th><th>Method</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>₹{x.amount.toLocaleString("en-IN")}</td><td>{x.method.toUpperCase()}</td><td><span className="pill">{x.status}</span></td></tr>)}</tbody></table></div></main>}
