import Nav from "@/components/Nav";import Footer from "@/components/Footer";import LuxuryBackground from "@/components/LuxuryBackground";import ReadMoreCard from "@/components/ReadMoreCard";import BundleCards from "@/components/BundleCards";import Link from "next/link";
export default function Home(){return <main className="shell"><LuxuryBackground/><Nav/>
<section className="hero heroLuxury premiumHero"><div className="heroEditorial"><div className="eyebrow">Luxury resin commerce · artist-led referral platform</div><h1>Beautiful products.<br/><em>A clearer way to grow.</em></h1><p className="heroLead">Growwmore connects handcrafted luxury resin décor with a product-based referral opportunity. Members first join through a real product collection, receive the physical products they chose, and only then unlock the referral ecosystem after payment approval.</p><div className="actions"><Link className="btn" href="/join">Create your account</Link><Link className="btn ghost" href="#experience">Discover Growwmore</Link></div><div className="heroMetrics"><div><strong>5</strong><span>launch collections</span></div><div><strong>₹1K–₹5.5K</strong><span>commission per eligible approved referral</span></div><div><strong>100%</strong><span>product-led model</span></div></div></div></section>

<section className="section editorialIntro" id="experience"><div className="sectionKicker">What Growwmore actually is</div><div className="editorial"><div><h2>Not a course. Not a promise of income. A real luxury product ecosystem.</h2></div><p className="sub">Growwmore is built for people who want to own premium resin décor and, if they choose, introduce those collections to others. The commercial relationship begins with a tangible product purchase—not a fee for access to an earning claim.</p></div></section>

<section className="section storyBand topBand"><div className="sectionHead"><div className="eyebrow">The foundation</div><h2>Designed around product value first.</h2></div><div className="storyGrid">
<ReadMoreCard index="01" title="Artist-first production" summary="Each collection represents handcrafted resin work, made with time, material and finishing effort." details="Growwmore is structured so the handmade product remains the center of the transaction. Because artists prepare items for actual orders, policies around cancellation and refunds are designed to protect completed custom production while still respecting applicable consumer law."/>
<ReadMoreCard index="02" title="A transparent referral model" summary="Members can refer genuine buyers and earn the listed commission only after an eligible sale is approved." details="Commission is not automatic for clicks, signups or unverified transactions. The referred purchase must satisfy the platform rules, payment must be approved, and abuse, duplicate/self-referral or chargeback activity can invalidate the commission." tone="olive"/>
<ReadMoreCard index="03" title="A premium member workspace" summary="Approved members receive a dashboard for referrals, earnings, wallet activity and payout requests." details="The dashboard is designed as an operating space rather than a static account page: members can see their collection, available earnings, referral code, referral link, referral activity and withdrawal history." tone="cream"/>
</div></section>

<section className="section visualStory"><div className="visualPanel visualMarble"><div><span>Material language</span><h2>Marble, stone, deep greens and quiet luxury.</h2><p>Our visual system is built from Black Olive #292E1E, deep marble #1A2529, forest #224141, mineral green #486664 and porcelain #E9E5DD—balanced across surfaces rather than filling every card with one flat colour.</p></div></div></section>

<section className="section storyBand midBand"><div className="sectionHead"><div className="eyebrow">How it works</div><h2>A simple, controlled journey.</h2></div><div className="journey premiumJourney"><div><b>01</b><h3>Create your account</h3><p>Email/password or Continue with Google. Email accounts receive verification.</p></div><div><b>02</b><h3>Choose a collection</h3><p>After account creation you enter the dedicated collection room and select a bundle.</p></div><div><b>03</b><h3>Complete payment</h3><p>Use the displayed UPI QR/ID, then submit the transaction reference for verification.</p></div><div><b>04</b><h3>Dashboard unlocks</h3><p>Founder approval activates the member workspace, referral tools and wallet.</p></div></div></section>

<section className="section packageGallery" id="packages"><div className="sectionHead"><div className="eyebrow">The collection library</div><h2>Five launch edits. Built like luxury product books.</h2><p className="sub">Browse the structure here. Account holders make the actual selection inside the dedicated collection room.</p></div><BundleCards selectable={false}/></section>

<section className="section storyBand bottomBand"><div className="sectionHead"><div className="eyebrow">Trust & operating principles</div><h2>Clear rules before growth.</h2></div><div className="storyGrid twoCol">
<ReadMoreCard index="A" title="Privacy by design" summary="We use account, payment-reference, referral and payout information only to operate the platform." details="Authentication is handled through Firebase. Passwords are not stored in Growwmore application documents. Access to sensitive operations is controlled by authentication and Firestore security rules." tone="olive"/>
<ReadMoreCard index="B" title="No guaranteed income" summary="Growwmore never treats package purchase as a promise of earnings, employment or fixed returns." details="Results depend on genuine approved sales. The platform displays the commission attached to each eligible collection, but actual earnings depend on member activity and valid completed referrals."/>
<ReadMoreCard index="C" title="Handmade-order refund policy" summary="Once production/dispatch reaches the protected stage, refunds are generally unavailable for handcrafted order value." details="Artists commit material and labour to made-for-order pieces. This protects creator loss. Nothing in the policy removes consumer rights that cannot legally be waived; damaged, incorrect or legally protected claims are reviewed under applicable law." tone="cream"/>
<ReadMoreCard index="D" title="Founder review & controls" summary="Payments and withdrawals move through controlled approval states before access or payout changes." details="The founder workspace includes payment verification, membership controls, referral oversight, package management, finance views and withdrawal processing." tone="olive"/>
</div><div className="legalLinks"><Link href="/legal/terms">Terms</Link><Link href="/legal/privacy">Privacy</Link><Link href="/legal/refund">Refund policy</Link><Link href="/legal/referral-terms">Referral terms</Link><Link href="/legal/commission-terms">Commission terms</Link></div></section>
<Footer/></main>}