import Nav from "@/components/Nav";import Footer from "@/components/Footer";import LuxuryBackground from "@/components/LuxuryBackground";import ReadMoreCard from "@/components/ReadMoreCard";import BundleCards from "@/components/BundleCards";import HomepageCms from "@/components/HomepageCms";import Link from "next/link";
export default function Home(){return <main className="shell"><LuxuryBackground/><Nav/>
<section className="hero heroLuxury premiumHero"><div className="heroEditorial"><div className="eyebrow">Luxury resin commerce · artist-led referral platform</div><h1>Beautiful products.<br/><em>A clearer way to grow.</em></h1><p className="heroLead">Growwmore connects handcrafted luxury resin décor with a product-based referral opportunity. Members first join through a real product collection, receive the physical products they chose, and only then unlock the referral ecosystem after payment approval.</p><div className="actions"><Link className="btn" href="/join">Create your account</Link><Link className="btn ghost" href="#experience">Discover Growwmore</Link></div><div className="heroMetrics"><div><strong>5</strong><span>launch collections</span></div><div><strong>₹1K–₹5.5K</strong><span>commission per eligible approved referral</span></div><div><strong>100%</strong><span>product-led model</span></div></div></div></section>

<section className="section editorialIntro" id="experience"><div className="sectionKicker">What Growwmore actually is</div><div className="editorial"><div><h2>A product marketplace built around homemade creativity, distribution and independent earning opportunity.</h2></div><p className="sub">Growwmore brings together artisan-made products, curated bundles, member referrals and a controlled payment-and-commission system. Buyers receive real products; approved members can share the marketplace using their referral link; artists gain another route to customers. The model is designed around genuine product value, not a fee charged only for access to an income promise.</p></div><div className="aboutGrid"><div><span>WHY IT EXISTS</span><h3>More reach for makers.</h3><p>Home-based creators can make exceptional products but often struggle with discovery, distribution and repeat demand. Growwmore is intended to give those products a structured commercial channel.</p></div><div><span>WHO IT IS FOR</span><h3>People who need flexibility.</h3><p>Students, homemakers, job seekers and working people looking for an additional product-led earning pathway can participate under clear referral and commission rules.</p></div><div><span>HOW VALUE MOVES</span><h3>Product → customer → verified sale → commission.</h3><p>The member shares a genuine collection. A customer makes an eligible purchase. Payment is verified. Only then can the applicable referral commission be recorded.</p></div></div></section>

<section className="section storyBand topBand"><div className="sectionHead"><div className="eyebrow">The foundation</div><h2>Designed around product value first.</h2></div><div className="storyGrid">
<ReadMoreCard index="01" title="Artist-first production" summary="Each collection represents handcrafted resin work, made with time, material and finishing effort." details="Growwmore is structured so the handmade product remains the center of the transaction. Because artists prepare items for actual orders, policies around cancellation and refunds are designed to protect completed custom production while still respecting applicable consumer law."/>
<ReadMoreCard index="02" title="A transparent referral model" summary="Members can refer genuine buyers and earn the listed commission only after an eligible sale is approved." details="Commission is not automatic for clicks, signups or unverified transactions. The referred purchase must satisfy the platform rules, payment must be approved, and abuse, duplicate/self-referral or chargeback activity can invalidate the commission." tone="olive"/>
<ReadMoreCard index="03" title="A premium member workspace" summary="Approved members receive a dashboard for referrals, earnings, wallet activity and payout requests." details="The dashboard is designed as an operating space rather than a static account page: members can see their collection, available earnings, referral code, referral link, referral activity and withdrawal history." tone="cream"/>
</div></section>

<HomepageCms fallback={{announcement:"Handmade products. Real value. A platform built to widen access to earning opportunities.",visionTitle:"A marketplace where more people can build an earning pathway around products made at home.",visionBody:"Growwmore’s vision is to make product-based earning opportunities more accessible to students, homemakers, people between jobs and anyone actively seeking a flexible way to earn. Members can promote genuine homemade and artisan products through a structured marketplace. Participation is an independent referral opportunity—not guaranteed employment, salary or fixed income—and earnings depend on valid approved sales.",founderName:"Syed Afshar Qadri",founderNote:"Syed Afshar Qadri founded Growwmore with a simple belief: valuable handmade work deserves stronger reach, and people who need flexible earning opportunities deserve a transparent system built around genuine products. Growwmore is being developed to connect home-based creators with customers while giving students, homemakers, job seekers and other aspiring earners a structured way to participate through approved product referrals—not income promises."}}/>

<section className="section storyBand midBand" id="how"><div className="sectionHead"><div className="eyebrow">How it works</div><h2>A simple, controlled journey.</h2></div><div className="journey premiumJourney"><div><b>01</b><h3>Create your account</h3><p>Email/password or Continue with Google. Email accounts receive verification.</p></div><div><b>02</b><h3>Choose a collection</h3><p>After account creation you enter the dedicated collection room and select a bundle.</p></div><div><b>03</b><h3>Complete payment</h3><p>Use the displayed UPI QR/ID, then submit the transaction reference for verification.</p></div><div><b>04</b><h3>Dashboard unlocks</h3><p>Founder approval activates the member workspace, referral tools and wallet.</p></div></div></section>

<section className="section packageGallery" id="collections"><div className="sectionHead"><div className="eyebrow">The collection library</div><h2>Five launch edits. Built like luxury product books.</h2><p className="sub">Browse the structure here. Account holders make the actual selection inside the dedicated collection room.</p></div><BundleCards selectable={false}/></section>

<section className="section storyBand bottomBand"><div className="sectionHead"><div className="eyebrow">Trust & operating principles</div><h2>Clear rules before growth.</h2></div><div className="storyGrid twoCol">
<ReadMoreCard index="A" title="Privacy by design" summary="We use account, payment-reference, referral and payout information only to operate the platform." details="Authentication is handled through Firebase. Passwords are not stored in Growwmore application documents. Access to sensitive operations is controlled by authentication and Firestore security rules." tone="olive"/>
<ReadMoreCard index="B" title="No guaranteed income" summary="Growwmore never treats package purchase as a promise of earnings, employment or fixed returns." details="Results depend on genuine approved sales. The platform displays the commission attached to each eligible collection, but actual earnings depend on member activity and valid completed referrals."/>
<ReadMoreCard index="C" title="Handmade-order refund policy" summary="Once production/dispatch reaches the protected stage, refunds are generally unavailable for handcrafted order value." details="Artists commit material and labour to made-for-order pieces. This protects creator loss. Nothing in the policy removes consumer rights that cannot legally be waived; damaged, incorrect or legally protected claims are reviewed under applicable law." tone="cream"/>
<ReadMoreCard index="D" title="Founder review & controls" summary="Payments and withdrawals move through controlled approval states before access or payout changes." details="The founder workspace includes payment verification, membership controls, referral oversight, package management, finance views and withdrawal processing." tone="olive"/>
</div><div className="legalLinks"><Link href="/legal/terms">Terms</Link><Link href="/legal/privacy">Privacy</Link><Link href="/legal/refund">Refund policy</Link><Link href="/legal/referral-terms">Referral terms</Link><Link href="/legal/commission-terms">Commission terms</Link></div></section>
<Footer/></main>}