import Footer from "@/components/Footer";import Nav from "@/components/Nav";import BundleCards from "@/components/BundleCards";import LuxuryBackground from "@/components/LuxuryBackground";
const pillars=[
 ["Real products first","Growwmore is not a fee-for-access scheme. Every launch bundle represents handcrafted resin décor created for the member’s order."],
 ["Artist-led fulfilment","Independent makers invest materials, curing time, finishing and packaging into each order. Our policies are designed to protect that work."],
 ["Transparent referrals","Members may refer eligible buyers and earn the published commission only after the referred purchase is verified and approved."],
 ["No income promises","Growwmore does not promise salary, fixed returns, passive income or guaranteed sales. Results depend on genuine customer purchases."],
 ["Luxury with purpose","Our long-term vision is to connect premium resin craftsmanship, digital commerce and responsible referral distribution in one experience."],
 ["Controlled access","Member dashboards unlock after payment approval. Wallet, referrals and withdrawals remain tied to verified account activity."]
];
export default function Home(){return <main className="shell"><LuxuryBackground/><Nav/><section className="hero heroLuxury"><div className="heroGlass"><div className="eyebrow">Luxury resin commerce · Built around real products</div><h1>Crafted to be owned.<br/><em>Designed to be shared.</em></h1><p>Growwmore is a product-based luxury resin platform where members choose a handcrafted décor bundle, receive real products, and can participate in a clearly disclosed referral programme after account activation.</p><div className="actions"><a className="btn" href="/join">Create your account</a><a className="btn ghost" href="#vision">Discover the vision</a></div><div className="heroTrust"><span>Real product bundles</span><span>Manual payment verification</span><span>Published commissions</span><span>No guaranteed earnings</span></div></div></section>
<section className="section editorial" id="vision"><div><div className="eyebrow">The Growwmore vision</div><h2>Make artisan luxury more discoverable — and distribution more human.</h2></div><p className="lead">Traditional luxury décor can be difficult for emerging artists to distribute at scale. Growwmore is designed as the bridge: handcrafted resin products remain the centre of the transaction, while verified members can introduce those products to new buyers through a transparent referral model.</p></section>
<section className="section"><div className="sectionHead"><div className="eyebrow">What Growwmore actually is</div><h2>A product experience first. A referral layer second.</h2></div><div className="pillarGrid">{pillars.map(([t,d],i)=><article className="luxCard" key={t}><span className="cardIndex">0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="section" id="how"><div className="eyebrow">The member journey</div><h2>Account → bundle → payment → approval → dashboard.</h2><div className="journey"><div><b>01</b><h3>Create your account</h3><p>Register with email/password or Continue with Google. Email/password accounts receive a verification email.</p></div><div><b>02</b><h3>Choose your bundle</h3><p>After registration, compare the five luxury launch bundles on a dedicated collection page.</p></div><div><b>03</b><h3>Complete payment</h3><p>Use the displayed UPI QR/ID, submit the UTR and wait for founder verification.</p></div><div><b>04</b><h3>Unlock Growwmore</h3><p>Approved accounts receive dashboard, referral, wallet, profile and withdrawal access.</p></div></div></section>
<section className="section" id="collections"><div className="sectionHead"><div className="eyebrow">Launch collection</div><h2>Five curated bundle editions.</h2><p className="lead">The imagery previously shared is treated only as product-category reference. Final handcrafted designs may differ because resin art is individually made.</p></div><BundleCards/></section>
<section className="section manifesto"><div className="manifestoCard"><div className="eyebrow">Artist-first order policy</div><h2>Made for your order, not pulled from a warehouse shelf.</h2><p>Resin pieces require materials, casting, curing, finishing and protective packing. Once an order enters production or is dispatched, it cannot simply be returned to inventory without creating a direct loss for the artist. Read the No-Refund Policy before purchasing.</p><a className="textLink" href="/legal/refund">Read the complete policy →</a></div><div className="manifestoCard olive"><div className="eyebrow">Responsible participation</div><h2>Share products — never earnings promises.</h2><p>Referral commissions apply only to eligible, verified purchases. Members must not market Growwmore as employment, investment, guaranteed income or a fixed-return opportunity.</p><a className="textLink" href="/legal/referral-terms">Read referral terms →</a></div></section><Footer/></main>}
