"use client";
import Link from "next/link";import {usePathname,useRouter} from "next/navigation";import {useState} from "react";import {signOut} from "firebase/auth";import {auth} from "@/lib/firebase";import {isAdminEmail} from "@/lib/constants";
const links=[
 ["/dashboard","Overview","Earnings snapshot"],["/dashboard/transactions","Transactions","Commission & payout ledger"],["/dashboard/team","Team members","Direct team & earnings"],["/dashboard/referrals","Referrals","Referral activity"],["/dashboard/wallet","Wallet","Balance & ledger"],["/dashboard/withdrawals","Withdrawals","Request and track payouts"],["/dashboard/profile","Profile","Account & payout details"]
];
export default function DashboardNav(){const path=usePathname(),router=useRouter(),[open,setOpen]=useState(false),admin=isAdminEmail(auth.currentUser?.email);return <>
 <nav className="nav dashboardTopbar"><Link className="brand" href="/dashboard">GROWW<span>MORE</span></Link><div className="navlinks">{admin&&<Link className="btn ghost hideSmall" href="/admin">Admin OS</Link>}<button className="menuButton" aria-label="Open dashboard menu" aria-expanded={open} onClick={()=>setOpen(true)}><i/><i/><i/></button></div></nav>
 {open&&<button className="menuBackdrop" aria-label="Close menu" onClick={()=>setOpen(false)}/>}<aside className={`dashboardDrawer ${open?"open":""}`}><div className="drawerHead"><div><small>MEMBER OS</small><strong>Main menu</strong></div><button onClick={()=>setOpen(false)}>×</button></div><div className="drawerLinks">{links.map(([href,label,meta])=><Link onClick={()=>setOpen(false)} className={path===href?"active":""} key={href} href={href}><span>{label}</span><small>{meta}</small></Link>)}</div>{admin&&<Link className="drawerAdmin" href="/admin" onClick={()=>setOpen(false)}>Open Founder Admin OS →</Link>}<button className="drawerSignout" onClick={()=>signOut(auth).then(()=>router.push("/"))}>Sign out</button></aside>
 </>}
